name: Build and Sign Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: 'v2.4.3'

      - name: Verify Cosign Installation
        run: cosign version

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t saivenkatvaraprasady/n8n-app2:latest .

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push saivenkatvaraprasady/n8n-app2:latest

      - name: Write signing key to disk
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
        shell: bash

      - name: Sign Docker image
        run: cosign sign --key cosign.key --yes saivenkatvaraprasady/n8n-app2:latest
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Verify Signature
        run: cosign verify --key cosign.pub saivenkatvaraprasady/n8n-app2:latest
