name: Build and Sign Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/n8n-app2:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/n8n-app2:latest

      - name: Restore Cosign keys from GitHub Secrets
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub

      - name: Sign Docker image
        run: |
          cosign sign --key cosign.key --yes ${{ secrets.DOCKER_USERNAME }}/n8n-app2:latest

      - name: Verify Docker image
        run: |
          ls -l  # Debugging: list files to confirm cosign.pub exists
          cat cosign.pub | head -n 5  # Debugging: preview public key
          cosign verify --key cosign.pub ${{ secrets.DOCKER_USERNAME }}/n8n-app2:latest
