name: Build and Sign Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: saivenkatvaraprasady/n8n-node-app:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Get image digest
        id: digest
        run: |
          docker buildx imagetools inspect saivenkatvaraprasady/n8n-node-app:latest --raw > raw.json
          echo "digest=$(jq -r '.manifests[0].digest' raw.json)" >> $GITHUB_OUTPUT

      - name: Sign Docker image
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          cosign sign --key cosign.key --yes "saivenkatvaraprasady/n8n-node-app@${{ steps.digest.outputs.digest }}"
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: ✅ Verify Signed Image
        run: |
          cosign verify --key <(echo "${{ secrets.COSIGN_PUBLIC_KEY }}") "saivenkatvaraprasady/n8n-node-app@${{ steps.digest.outputs.digest }}" || echo "Verification failed"
